### ISSUE TITLE
1 byte dynamic allocation?

### ISSUE THREAD

**Issue by ghost** [dlarudgus20/ClubcChat2Srv#1]
line 7 from ClubcChat2Srv/ClubcChat2Srv/CharConvert.cpp, there is 1 byte allocation, is it intended?

**Comment by dlarudgus20** [comment]
@x86poem Thank you for you to comment :)

The purpose of this repo is just archiving old dirty project, so there might ( in fact, must ) be some errors. But I think the point you commented has no problem.

```
char *ret = (char *)calloc(len, sizeof(char));
```

That's not 1 byte allocation. `calloc()` allocates memory in size of `arg_first * arg_second`. For more information, see [cppreference](http://en.cppreference.com/w/cpp/memory/c/calloc)
